### ISSUE TITLE
Include baserunners who are put out

### ISSUE THREAD

**Issue by no-space** [lilserf/Cauldron#24]
Baserunners who are put out on a play as a result of caught stealing, fielders choice, etc, currently do not appear in the base_runners events for the associated play. Ideally, the behavior would be for them to still appear in the play and either have base_after_play = 0, or to have a separate "out" flag, to denote that the runner was put out during the play.

**Comment by lilserf** [comment]
Should be fixed in 1.10.0 (prophesizer 1.2.2, deployed now), with base_after_play = 0
