### ISSUE TITLE
Game Event with null batter ID.

### ISSUE THREAD

**Issue by Corvimae** [lilserf/Cauldron#4]
Not entirely possible what's making it happen, but I'm seeing some game events that do not have a `batterId`.

Example file: `blaseball-log-1596003134151.json.gz`

![image](https://user-images.githubusercontent.com/236379/89718880-687ca400-d988-11ea-8833-df00d1d4963d.png)

**Comment by lilserf** [comment]
I fixed at least one way this was happening but some of them are just bad data where we never get an update that has a valid batterId before the event ends.
