### ISSUE TITLE
Baserunners appear to not be correctly updated after a play.

### ISSUE THREAD

**Issue by Corvimae** [lilserf/Cauldron#6]
If a runner is batted in, there does not appear to be a baserunner record acknowledging that. The play should have a record with `base_after_play` set to 0 or 4 (ideally 4).

The responsible pitcher also seems to be always set to the current pitcher, regardless of who was actually responsible.

**Comment by lilserf** [comment]
I opened a separate issue for the responsible pitcher bit;
Submitted some changes that should properly show runners advancing to base 4 when they score
